"""
ClimateGuard Expert Rule Engine — engine.py
Part 3

Provides ExpertRuleEngine: evaluates all seven deterministic expert rules
against a feature record and returns a structured list of RuleResult objects.

The engine:
    - Takes a feature record (dict or pd.Series) plus optional Part 2 context
      (risk_level, heatwave_probability) as inputs.
    - Returns a list of RuleResult objects — one per rule.
    - Is stateless and deterministic.
    - Does NOT call the ML predictor or the Part 2 engine.

Position in the pipeline
------------------------
    Part 2 output (risk_level, heatwave_probability)
        + feature record (for temperature / anomaly values)
        ↓
    ExpertRuleEngine.evaluate(...)
        ↓
    List[RuleResult] — expert contextual overlays

IMPORTANT DISCLAIMER
--------------------
Expert rules are project-defined contextual guidance for research and
educational purposes.  They are NOT official IMD warnings, NOT official
government heat action plan outputs, and NOT certified medical advice.
Always follow guidance from local authorities during heat emergencies.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Union

import pandas as pd

from src.expert_rules.rules import (
    RuleResult,
    evaluate_rule_01,
    evaluate_rule_02,
    evaluate_rule_03,
    evaluate_rule_04,
    evaluate_rule_05,
    evaluate_rule_06,
    evaluate_rule_07,
)

# ---------------------------------------------------------------------------
# Disclaimer
# ---------------------------------------------------------------------------

EXPERT_RULES_DISCLAIMER = (
    "Expert rule results are project-defined contextual guidance generated by "
    "ClimateGuard Part 3.  They are NOT official India Meteorological Department "
    "(IMD) warnings, NOT official government heat action plan outputs, and NOT "
    "certified medical advice.  Always follow guidance from your local authorities "
    "and health professionals during heat emergencies."
)


# ---------------------------------------------------------------------------
# ExpertRuleEngine
# ---------------------------------------------------------------------------

class ExpertRuleEngine:
    """
    Evaluates all seven ClimateGuard expert rules for a given feature record.

    The engine is stateless.  Each call to evaluate() produces an independent
    result based solely on the supplied inputs.

    Rules evaluated
    ---------------
    RULE_01 — Extreme Temperature
    RULE_02 — Persistent Heat
    RULE_03 — High Nighttime Temperature
    RULE_04 — Compounded Heat Stress
    RULE_05 — Vulnerable Population Alert
    RULE_06 — Outdoor Exposure Warning
    RULE_07 — Hydration and Cooling Reminder

    Usage
    -----
        engine = ExpertRuleEngine()

        results = engine.evaluate(
            data=feature_dict,
            risk_level="HIGH",
            heatwave_probability=0.72,
        )

        for r in results:
            print(r.rule_id, r.triggered, r.severity)

        # Triggered rules only
        triggered = engine.get_triggered(results)

        # As dicts (for JSON serialisation)
        dicts = engine.to_dict_list(results)
    """

    # Expose the disclaimer as a class attribute for downstream use
    DISCLAIMER = EXPERT_RULES_DISCLAIMER

    # ------------------------------------------------------------------
    # Main evaluation method
    # ------------------------------------------------------------------

    def evaluate(
        self,
        data: Union[Dict, pd.Series],
        risk_level: Optional[str] = None,
        heatwave_probability: Optional[float] = None,
    ) -> List[RuleResult]:
        """
        Evaluate all seven expert rules against a feature record.

        Parameters
        ----------
        data : dict or pd.Series
            Feature record.  Must contain at minimum 'temperature_2m_max'.
            May contain any or all of the 110 model features — rules use only
            the fields they need and skip gracefully if a field is absent.
        risk_level : str, optional
            Part 2 risk level ("LOW" / "MODERATE" / "HIGH" / "EXTREME").
            Required for RULE_05 and RULE_06 to fire.  If None, those rules
            will not trigger.
        heatwave_probability : float, optional
            Part 1 model heatwave probability [0, 1].
            Used by RULE_07.  If None, RULE_07 uses only the temperature fallback.

        Returns
        -------
        list of RuleResult
            One RuleResult per rule, in rule order (01 → 07).
            All seven results are always returned (triggered=True/False).
        """
        if isinstance(data, pd.Series):
            record = data.to_dict()
        elif isinstance(data, dict):
            record = data
        else:
            raise TypeError(
                f"data must be a dict or pd.Series; got {type(data).__name__}."
            )

        results: List[RuleResult] = [
            evaluate_rule_01(record),
            evaluate_rule_02(record),
            evaluate_rule_03(record),
            evaluate_rule_04(record),
            evaluate_rule_05(record, risk_level=risk_level),
            evaluate_rule_06(record, risk_level=risk_level),
            evaluate_rule_07(record, heatwave_probability=heatwave_probability),
        ]
        return results

    # ------------------------------------------------------------------
    # Helper methods
    # ------------------------------------------------------------------

    @staticmethod
    def get_triggered(results: List[RuleResult]) -> List[RuleResult]:
        """Return only the rules that were triggered."""
        return [r for r in results if r.triggered]

    @staticmethod
    def get_by_severity(
        results: List[RuleResult],
        severity: str,
    ) -> List[RuleResult]:
        """
        Return rules with a specific severity level.

        Parameters
        ----------
        results  : list of RuleResult
        severity : "INFO" | "WARNING" | "CRITICAL"
        """
        return [r for r in results if r.severity.upper() == severity.upper()]

    @staticmethod
    def to_dict_list(results: List[RuleResult]) -> List[Dict]:
        """Convert a list of RuleResult objects to a list of plain dicts."""
        return [r.to_dict() for r in results]

    @staticmethod
    def triggered_count(results: List[RuleResult]) -> int:
        """Return the count of triggered rules."""
        return sum(1 for r in results if r.triggered)

    @staticmethod
    def highest_severity(results: List[RuleResult]) -> Optional[str]:
        """
        Return the highest severity level among triggered rules.

        Returns "CRITICAL" > "WARNING" > "INFO" > None (if no rules triggered).
        """
        _order = {"CRITICAL": 3, "WARNING": 2, "INFO": 1}
        triggered = [r for r in results if r.triggered]
        if not triggered:
            return None
        return max(triggered, key=lambda r: _order.get(r.severity.upper(), 0)).severity

    def summarise(self, results: List[RuleResult]) -> Dict:
        """
        Return a summary dict of a rule evaluation.

        Returns
        -------
        dict with keys:
            total_rules, triggered_count, highest_severity,
            triggered_ids, disclaimer
        """
        triggered = self.get_triggered(results)
        return {
            "total_rules":       len(results),
            "triggered_count":   len(triggered),
            "highest_severity":  self.highest_severity(results),
            "triggered_ids":     [r.rule_id for r in triggered],
            "disclaimer":        EXPERT_RULES_DISCLAIMER,
        }

    def __repr__(self) -> str:
        return "ExpertRuleEngine(rules=[RULE_01..RULE_07], stateless)"
